sudo: required
dist: trusty
os: linux
language: ruby
rvm:
  - 2.2
  - jruby

script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_ros_install.bash
